<a href="https://colab.research.google.com/github/yohangumiel/Aulas-PUC-PR/blob/main/feature_selection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://pythonguides.com/scikit-learn-genetic-algorithm/

In [2]:
!pip install sklearn-genetic

In [16]:
from __future__ import print_function
import numpy as np
from sklearn import datasets, linear_model
from sklearn.svm import SVC
from genetic_selection import GeneticSelectionCV
import urllib.request
from sklearn import tree
from sklearn import  model_selection
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import classification_report


In [4]:
url = "http://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data"
raw_data = urllib.request.urlopen(url)

# Carrega arquivo como uma matriz
dataset = np.loadtxt(raw_data, delimiter=",")

# Observe que na base Wine a classe eh primeiro atributo 
X = dataset[:,1:13]
y = dataset[:,0]




In [5]:
X

array([[14.23,  1.71,  2.43, ...,  5.64,  1.04,  3.92],
       [13.2 ,  1.78,  2.14, ...,  4.38,  1.05,  3.4 ],
       [13.16,  2.36,  2.67, ...,  5.68,  1.03,  3.17],
       ...,
       [13.27,  4.28,  2.26, ..., 10.2 ,  0.59,  1.56],
       [13.17,  2.59,  2.37, ...,  9.3 ,  0.6 ,  1.62],
       [14.13,  4.1 ,  2.74, ...,  9.2 ,  0.61,  1.6 ]])

In [6]:
y

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3.])

In [7]:
np.unique(y)

array([1., 2., 3.])

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=.2, random_state=42, stratify=y)


In [9]:


estimators = svm.SVC()

selectors = GeneticSelectionCV(estimators,
                                cv=6,
                                verbose=1,
                                scoring="f1_micro",
                                n_jobs=-1)

selectors = selectors.fit(X_train, y_train)

print(selectors.support_)

Selecting features with genetic algorithm.
gen	nevals	avg                            	std                            	min                            	max                               
0  	300   	[ 0.648113  6.74      0.057709]	[ 0.140981  3.344508  0.01885 ]	[ 0.513285  1.        0.017334]	[  0.943841  12.         0.123963]
1  	179   	[ 0.774731  5.713333  0.062724]	[ 0.141817  2.772091  0.023547]	[ 0.528986  1.        0.017334]	[  0.950785  12.         0.123963]
2  	192   	[ 0.877769  5.413333  0.06415 ]	[ 0.076103  1.998955  0.024567]	[ 0.528986  1.        0.017334]	[  0.950785  11.         0.123963]
3  	165   	[ 0.91518  5.92     0.06022]   	[ 0.055807  1.593821  0.022932]	[ 0.522041  2.        0.017334]	[ 0.950785  9.        0.123963]   
4  	194   	[ 0.927225  6.493333  0.057246]	[ 0.059754  1.066125  0.014618]	[ 0.543176  3.        0.021178]	[ 0.957729  9.        0.123963]   
5  	167   	[ 0.941938  6.476667  0.05505 ]	[ 0.03406   0.977815  0.009081]	[ 0.53593   4.        0.031389

In [10]:
print(selectors.support_)

[ True  True  True False False False  True  True False  True False  True]


In [13]:
y_pred = selectors.predict(X_test)

In [14]:
confusion_matrix(y_test,y_pred)

array([[11,  1,  0],
       [ 2, 12,  0],
       [ 0,  1,  9]])

In [18]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         1.0       0.85      0.92      0.88        12
         2.0       0.86      0.86      0.86        14
         3.0       1.00      0.90      0.95        10

    accuracy                           0.89        36
   macro avg       0.90      0.89      0.89        36
weighted avg       0.89      0.89      0.89        36



## SEM FEATURE SELECTION

In [20]:
estimators1 = svm.SVC()
estimators1.fit(X_train,y_train)
y_pred1 = estimators1.predict(X_test)

In [21]:
confusion_matrix(y_test,y_pred1)

array([[10,  2,  0],
       [ 4, 10,  0],
       [ 3,  7,  0]])

In [22]:
print(classification_report(y_test,y_pred1))

              precision    recall  f1-score   support

         1.0       0.59      0.83      0.69        12
         2.0       0.53      0.71      0.61        14
         3.0       0.00      0.00      0.00        10

    accuracy                           0.56        36
   macro avg       0.37      0.52      0.43        36
weighted avg       0.40      0.56      0.47        36



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
